### ISSUE TITLE
New GA4 measurement ID format

### ISSUE THREAD

**Issue by albanbochsler** [matthiask/django-privacy-killer#3]
The GA4 property collects data via a different ID than Universal Analytics. The HTML-Snippet looks like below: 

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-1234567890"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-1234567890');
</script>
```

**Comment by matthiask** [comment]
https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization We should probably add this by default too?
See https://github.com/matthiask/django-privacy-killer/blob/d03d694458ae4890b9fab9be13ecdaced5103333/privacy_killer/templates/privacy_killer/google_analytics_head.html#L5
